export const americaCountries = {
    "AI": "Anguilla",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AW": "Aruba",
    "BS": "Bahamas",
    "BB": "Barbados",
    "BZ": "Belize",
    "BM": "Bermuda",
    "BO": "Bolivia",
    "BQ": "Bonaire",
    "BR": "Brazil",
    "VG": "British Virgin Islands",
    "CA": "Canada",
    "KY": "Cayman Islands",
    "CL": "Chile",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CW": "Curaçao",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "SV": "El Salvador",
    "FK": "Falkland Islands",
    "GF": "French Guiana",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GT": "Guatemala",
    "GY": "Guyana",
    "HT": "Haiti",
    "HN": "Honduras",
    "JM": "Jamaica",
    "MQ": "Martinique",
    "MX": "Mexico",
    "MS": "Montserrat",
    "NI": "Nicaragua",
    "PA": "Panama",
    "PY": "Paraguay",
    "PE": "Peru",
    "PR": "Puerto Rico",
    "BL": "Saint Barthélemy",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "SX": "Sint Maarten",
    "SR": "Suriname",
    "TT": "Trinidad and Tobago",
    "TC": "Turks and Caicos Islands",
    "US": "United States",
    "UY": "Uruguay",
    "VE": "Venezuela",
    "VI": "Virgin Islands"
};
  